[workspace]
authors = ["Alex Jacob <alixjcob559@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "yolov10-max-architecture"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
modular = ">=25.5.0.dev2025062815,<26"
max = ">=25.5.0.dev2025062815,<26"
