version: '3.8'

services:
  yolov10-vision:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MAX_DEVICE=auto
      - MAX_PRECISION=fp16
      - MODEL_NAME=yolov10-vision
      - MODEL_VERSION=1.0.0
    volumes:
      - ./model:/app/model
      - ./config.json:/app/config.json
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
