apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolov10-vision
  labels:
    app: yolov10-vision
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yolov10-vision
  template:
    metadata:
      labels:
        app: yolov10-vision
    spec:
      containers:
      - name: yolov10-vision
        image: yolov10-vision:latest
        ports:
        - containerPort: 8000
        env:
        - name: MAX_DEVICE
          value: "auto"
        - name: MAX_PRECISION
          value: "fp16"
        - name: MODEL_NAME
          value: "yolov10-vision"
        - name: MODEL_VERSION
          value: "1.0.0"
        resources:
          limits:
            nvidia.com/gpu: 1
          requests:
            memory: "4Gi"
            cpu: "2"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: yolov10-vision-service
spec:
  selector:
    app: yolov10-vision
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
